language: ruby
rvm:
  - 1.9.3
  - 1.8.7
  - jruby-head
  - rbx-19mode
jdk:
  - openjdk7
bundler_args: "--without development"
script: "bundle exec rake test:all --trace"
install:
  - bundle install
notifications:
  email:
    - mi@mifo.sk
  irc:
    channels:
      - "irc.freenode.org#deltacloud"
    use_notice: true
    skip_join: false
