language: ruby
rvm:
  - "1.9.3"
  - "rbx-19mode"
  - "jruby-19mode"
bundler_args: "--without development"
before_install:
  - "gem install bundler -v 1.2.3"
script: "bundle exec rake --trace"
notifications:
  email:
    on_success: never
    on_failure: change
