
struct Contact {
    contactId   string
    username    string
    firstName   string
    lastName    string
}

interface ContactService {
    put(c Contact) string
    get(contactId string) Contact [optional]
    remove(contactId string) bool
}
