# http://about.travis-ci.org/docs/user/build-configuration/
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
gemfile: Gemfile.ci
notifications:
  recipients:
    - nesquena@gmail.com
    - databyte@gmail.com
matrix:
  allow_failures:
    - rvm: 1.8.7
